version: '3'

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  proto:
    desc: Generate Go code into pb subfolders
    cmds:
      # Create pb directories
      - powershell -Command "New-Item -ItemType Directory -Force be/orders/api/proto/pb, be/catalog/api/proto/pb, be/auth/api/proto/pb, be/kitchen/api/proto/pb, be/logistics/api/proto/pb, be/notification/api/proto/pb, be/treasury/api/proto/pb"
      # Generate files
      - protoc --proto_path=be/orders/api/proto --go_out=be/orders/api/proto --go-grpc_out=be/orders/api/proto be/orders/api/proto/*.proto
      - protoc --proto_path=be/catalog/api/proto --go_out=be/catalog/api/proto --go-grpc_out=be/catalog/api/proto be/catalog/api/proto/*.proto
      - protoc --proto_path=be/auth/api/proto --go_out=be/auth/api/proto --go-grpc_out=be/auth/api/proto be/auth/api/proto/*.proto
      - protoc --proto_path=be/kitchen/api/proto --go_out=be/kitchen/api/proto --go-grpc_out=be/kitchen/api/proto be/kitchen/api/proto/*.proto
      - protoc --proto_path=be/logistics/api/proto --go_out=be/logistics/api/proto --go-grpc_out=be/logistics/api/proto be/logistics/api/proto/*.proto
      - protoc --proto_path=be/notification/api/proto --go_out=be/notification/api/proto --go-grpc_out=be/notification/api/proto be/notification/api/proto/*.proto
      - protoc --proto_path=be/treasury/api/proto --go_out=be/treasury/api/proto --go-grpc_out=be/treasury/api/proto be/treasury/api/proto/*.proto

  docker-up:
    desc: Run infrastructure via docker-compose
    cmds:
      - docker-compose up --build -d

  docker-down:
    desc: Stop docker-compose
    cmds:
      - docker-compose down

  k8s-deploy:
    desc: Deploy all services to Kubernetes
    cmds:
      - kubectl apply -f deploy/k8s/namespace.yaml
      - kubectl apply -f deploy/k8s/
    
  k8s-undeploy:
    desc: Remove all services from Kubernetes
    cmds:
      - kubectl delete -f deploy/k8s/
