// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: kpi.proto

package analytics_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagerKPI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	PlanRevenue   float64                `protobuf:"fixed64,2,opt,name=plan_revenue,json=planRevenue,proto3" json:"plan_revenue,omitempty"`
	FactRevenue   float64                `protobuf:"fixed64,3,opt,name=fact_revenue,json=factRevenue,proto3" json:"fact_revenue,omitempty"`
	KpiPercent    float64                `protobuf:"fixed64,4,opt,name=kpi_percent,json=kpiPercent,proto3" json:"kpi_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerKPI) Reset() {
	*x = ManagerKPI{}
	mi := &file_kpi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerKPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerKPI) ProtoMessage() {}

func (x *ManagerKPI) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerKPI.ProtoReflect.Descriptor instead.
func (*ManagerKPI) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerKPI) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ManagerKPI) GetPlanRevenue() float64 {
	if x != nil {
		return x.PlanRevenue
	}
	return 0
}

func (x *ManagerKPI) GetFactRevenue() float64 {
	if x != nil {
		return x.FactRevenue
	}
	return 0
}

func (x *ManagerKPI) GetKpiPercent() float64 {
	if x != nil {
		return x.KpiPercent
	}
	return 0
}

var File_kpi_proto protoreflect.FileDescriptor

const file_kpi_proto_rawDesc = "" +
	"\n" +
	"\tkpi.proto\x12\fanalytics.v1\"\x92\x01\n" +
	"\n" +
	"ManagerKPI\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\x12!\n" +
	"\fplan_revenue\x18\x02 \x01(\x01R\vplanRevenue\x12!\n" +
	"\ffact_revenue\x18\x03 \x01(\x01R\vfactRevenue\x12\x1f\n" +
	"\vkpi_percent\x18\x04 \x01(\x01R\n" +
	"kpiPercentB\x13Z\x11./pb;analytics_pbb\x06proto3"

var (
	file_kpi_proto_rawDescOnce sync.Once
	file_kpi_proto_rawDescData []byte
)

func file_kpi_proto_rawDescGZIP() []byte {
	file_kpi_proto_rawDescOnce.Do(func() {
		file_kpi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kpi_proto_rawDesc), len(file_kpi_proto_rawDesc)))
	})
	return file_kpi_proto_rawDescData
}

var file_kpi_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kpi_proto_goTypes = []any{
	(*ManagerKPI)(nil), // 0: analytics.v1.ManagerKPI
}
var file_kpi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kpi_proto_init() }
func file_kpi_proto_init() {
	if File_kpi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kpi_proto_rawDesc), len(file_kpi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kpi_proto_goTypes,
		DependencyIndexes: file_kpi_proto_depIdxs,
		MessageInfos:      file_kpi_proto_msgTypes,
	}.Build()
	File_kpi_proto = out.File
	file_kpi_proto_goTypes = nil
	file_kpi_proto_depIdxs = nil
}
