// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: kpi.proto

package analytics_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KpiService_GetManagerKPI_FullMethodName = "/analytics.v1.KpiService/GetManagerKPI"
)

// KpiServiceClient is the client API for KpiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KpiServiceClient interface {
	GetManagerKPI(ctx context.Context, in *KpiRequest, opts ...grpc.CallOption) (*KpiResponse, error)
}

type kpiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKpiServiceClient(cc grpc.ClientConnInterface) KpiServiceClient {
	return &kpiServiceClient{cc}
}

func (c *kpiServiceClient) GetManagerKPI(ctx context.Context, in *KpiRequest, opts ...grpc.CallOption) (*KpiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KpiResponse)
	err := c.cc.Invoke(ctx, KpiService_GetManagerKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KpiServiceServer is the server API for KpiService service.
// All implementations must embed UnimplementedKpiServiceServer
// for forward compatibility.
type KpiServiceServer interface {
	GetManagerKPI(context.Context, *KpiRequest) (*KpiResponse, error)
	mustEmbedUnimplementedKpiServiceServer()
}

// UnimplementedKpiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKpiServiceServer struct{}

func (UnimplementedKpiServiceServer) GetManagerKPI(context.Context, *KpiRequest) (*KpiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManagerKPI not implemented")
}
func (UnimplementedKpiServiceServer) mustEmbedUnimplementedKpiServiceServer() {}
func (UnimplementedKpiServiceServer) testEmbeddedByValue()                    {}

// UnsafeKpiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KpiServiceServer will
// result in compilation errors.
type UnsafeKpiServiceServer interface {
	mustEmbedUnimplementedKpiServiceServer()
}

func RegisterKpiServiceServer(s grpc.ServiceRegistrar, srv KpiServiceServer) {
	// If the following call panics, it indicates UnimplementedKpiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KpiService_ServiceDesc, srv)
}

func _KpiService_GetManagerKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KpiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KpiServiceServer).GetManagerKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KpiService_GetManagerKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KpiServiceServer).GetManagerKPI(ctx, req.(*KpiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KpiService_ServiceDesc is the grpc.ServiceDesc for KpiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KpiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.KpiService",
	HandlerType: (*KpiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManagerKPI",
			Handler:    _KpiService_GetManagerKPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kpi.proto",
}
