// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: chat.proto

package chat_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientMessage_Connect
	//	*ClientMessage_SendMessage
	//	*ClientMessage_ReadMessage
	Event         isClientMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetEvent() isClientMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientMessage) GetConnect() *ConnectEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientMessage_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *ClientMessage) GetSendMessage() *SendMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ClientMessage) GetReadMessage() *ReadMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientMessage_ReadMessage); ok {
			return x.ReadMessage
		}
	}
	return nil
}

type isClientMessage_Event interface {
	isClientMessage_Event()
}

type ClientMessage_Connect struct {
	Connect *ConnectEvent `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type ClientMessage_SendMessage struct {
	SendMessage *SendMessageEvent `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ClientMessage_ReadMessage struct {
	ReadMessage *ReadMessageEvent `protobuf:"bytes,3,opt,name=read_message,json=readMessage,proto3,oneof"`
}

func (*ClientMessage_Connect) isClientMessage_Event() {}

func (*ClientMessage_SendMessage) isClientMessage_Event() {}

func (*ClientMessage_ReadMessage) isClientMessage_Event() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_NewMessage
	//	*ServerMessage_Error
	Event         isServerMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetEvent() isServerMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerMessage) GetAck() *MessageAck {
	if x != nil {
		if x, ok := x.Event.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetNewMessage() *NewMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerMessage_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Event interface {
	isServerMessage_Event()
}

type ServerMessage_Ack struct {
	Ack *MessageAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerMessage_NewMessage struct {
	NewMessage *NewMessageEvent `protobuf:"bytes,2,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorEvent `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Ack) isServerMessage_Event() {}

func (*ServerMessage_NewMessage) isServerMessage_Event() {}

func (*ServerMessage_Error) isServerMessage_Event() {}

type ConnectEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectEvent) Reset() {
	*x = ConnectEvent{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectEvent) ProtoMessage() {}

func (x *ConnectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectEvent.ProtoReflect.Descriptor instead.
func (*ConnectEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConnectEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConnectEvent) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

type SendMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageEvent) Reset() {
	*x = SendMessageEvent{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageEvent) ProtoMessage() {}

func (x *SendMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageEvent.ProtoReflect.Descriptor instead.
func (*SendMessageEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendMessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReadMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageEvent) Reset() {
	*x = ReadMessageEvent{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageEvent) ProtoMessage() {}

func (x *ReadMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageEvent.ProtoReflect.Descriptor instead.
func (*ReadMessageEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMessageEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *MessageAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MessageAck) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type NewMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SenderName    string                 `protobuf:"bytes,6,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageEvent) Reset() {
	*x = NewMessageEvent{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageEvent) ProtoMessage() {}

func (x *NewMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageEvent.ProtoReflect.Descriptor instead.
func (*NewMessageEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *NewMessageEvent) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NewMessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NewMessageEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NewMessageEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NewMessageEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NewMessageEvent) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SenderName    string                 `protobuf:"bytes,8,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\rClientMessage\x12.\n" +
	"\aconnect\x18\x01 \x01(\v2\x12.chat.ConnectEventH\x00R\aconnect\x12;\n" +
	"\fsend_message\x18\x02 \x01(\v2\x16.chat.SendMessageEventH\x00R\vsendMessage\x12;\n" +
	"\fread_message\x18\x03 \x01(\v2\x16.chat.ReadMessageEventH\x00R\vreadMessageB\a\n" +
	"\x05event\"\xa2\x01\n" +
	"\rServerMessage\x12$\n" +
	"\x03ack\x18\x01 \x01(\v2\x10.chat.MessageAckH\x00R\x03ack\x128\n" +
	"\vnew_message\x18\x02 \x01(\v2\x15.chat.NewMessageEventH\x00R\n" +
	"newMessage\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x10.chat.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"w\n" +
	"\fConnectEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\"E\n" +
	"\x10SendMessageEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"1\n" +
	"\x10ReadMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"J\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"\xcf\x01\n" +
	"\x0fNewMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vsender_name\x18\x06 \x01(\tR\n" +
	"senderName\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x11GetHistoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"?\n" +
	"\x12GetHistoryResponse\x12)\n" +
	"\bmessages\x18\x01 \x03(\v2\r.chat.MessageR\bmessages\"\xee\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vsender_name\x18\b \x01(\tR\n" +
	"senderName2\x87\x01\n" +
	"\vChatService\x127\n" +
	"\aConnect\x12\x13.chat.ClientMessage\x1a\x13.chat.ServerMessage(\x010\x01\x12?\n" +
	"\n" +
	"GetHistory\x12\x17.chat.GetHistoryRequest\x1a\x18.chat.GetHistoryResponseB\x0eZ\f./pb;chat_pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chat_proto_goTypes = []any{
	(*ClientMessage)(nil),         // 0: chat.ClientMessage
	(*ServerMessage)(nil),         // 1: chat.ServerMessage
	(*ConnectEvent)(nil),          // 2: chat.ConnectEvent
	(*SendMessageEvent)(nil),      // 3: chat.SendMessageEvent
	(*ReadMessageEvent)(nil),      // 4: chat.ReadMessageEvent
	(*MessageAck)(nil),            // 5: chat.MessageAck
	(*NewMessageEvent)(nil),       // 6: chat.NewMessageEvent
	(*ErrorEvent)(nil),            // 7: chat.ErrorEvent
	(*GetHistoryRequest)(nil),     // 8: chat.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 9: chat.GetHistoryResponse
	(*Message)(nil),               // 10: chat.Message
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	2,  // 0: chat.ClientMessage.connect:type_name -> chat.ConnectEvent
	3,  // 1: chat.ClientMessage.send_message:type_name -> chat.SendMessageEvent
	4,  // 2: chat.ClientMessage.read_message:type_name -> chat.ReadMessageEvent
	5,  // 3: chat.ServerMessage.ack:type_name -> chat.MessageAck
	6,  // 4: chat.ServerMessage.new_message:type_name -> chat.NewMessageEvent
	7,  // 5: chat.ServerMessage.error:type_name -> chat.ErrorEvent
	11, // 6: chat.NewMessageEvent.created_at:type_name -> google.protobuf.Timestamp
	10, // 7: chat.GetHistoryResponse.messages:type_name -> chat.Message
	11, // 8: chat.Message.created_at:type_name -> google.protobuf.Timestamp
	0,  // 9: chat.ChatService.Connect:input_type -> chat.ClientMessage
	8,  // 10: chat.ChatService.GetHistory:input_type -> chat.GetHistoryRequest
	1,  // 11: chat.ChatService.Connect:output_type -> chat.ServerMessage
	9,  // 12: chat.ChatService.GetHistory:output_type -> chat.GetHistoryResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Connect)(nil),
		(*ClientMessage_SendMessage)(nil),
		(*ClientMessage_ReadMessage)(nil),
	}
	file_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_NewMessage)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
